### ISSUE TITLE
How do you parse array JSONValues?

### ISSUE THREAD

**Issue by ryanbooker** [typelift/Tyro#10]
I am interacting with an API that returns a JSON array. This is correctly transformed into a `JSONValue`, but how do I then parse that `JSONValue`? I happen to be using the older Swiftz version of this.

This works if the `JSONValue` is a `.JSONObject` with a "results" key.

```
func getResults(x: JSONValue) -> [A]? {
    let a: [A]? = x <? "results"
    return a
}
```

However if the `JSONValue` is a `.JSONArray` I'm not sure how to proceed, save manually matching. Is this the correct way to do it, or is there another operator to use or something else I'm missing?

```
func getResults(x: JSONValue) -> [A]? {
    switch x {
    case let .JSONArray(results):
        let a: [A]? = results.flatMap(A.fromJSON)
        return a
    default: return nil
    }
}
```

**Comment by mpurland** [comment]
In Tyro 0.0.1 and old Swiftz versions there are less options for encoding and decoding types. I would recommend using the latest version of Tyro.

This should solve your problem:

``` swift
func getResults(x: JSONValue) -> [A]? {
    let a: [A]? = JArray<A, A>.fromJSON(x)
    return a
}
```

Let me know if this helps.

**Comment by mpurland** [comment]
@ryanbooker Did that work for you?

**Comment by ryanbooker** [comment]
@mpurland Sorry, I missed your initial reply. That works. Thanks. I do plan to upgrade, I just haven't gotten around to it yet. Cheers. :)

**Comment by mpurland** [comment]
Great. Glad to have helped.
