### ISSUE TITLE
Retrieving nested JSONDecodable objects

### ISSUE THREAD

**Issue by ryanbooker** [typelift/Tyro#16]
e.g. A includes a list of Bs. The json returns As with nested Bs. The list of Bs may contain invalid Bs.

Is there a way to load the Bs without short circuiting and throwing out the whole list?

i.e. 

`let bs: [B]? = x <? "bs"` will return nil if a single B is bogus. Is there something like `let bs: [B?]? = x <? "bs"` so I could then flatMap the `[B?]` list to strip the bogus Bs? An operator I've missed for example? Am I simply misunderstanding something?

**Comment by CodaFi** [comment]
If I understand you correctly, you want us to provide a map for JSONValues.  That thing is not a Functor, and I would feel uneasy about allowing this; invalid JSON is invalid JSON.  Is there a way you can use a more general type or alter the API in question so it won't generate these kinds of cases?

**Comment by ryanbooker** [comment]
Makes sense. I think I can work around by making more of the properties optional and deal with the client side I guess. It is bad data, so it really should be fixed at the server. Thanks. It's frustrating that one bad record invalidates the entire thing though. There could be 200 Bs and if one is missing a property the whole list is rejected.

**Comment by CodaFi** [comment]
You can provide this yourself in an extension to JSONValue fwiw.  I'm just responding to the "is there something I'm missing" part.

**Comment by ryanbooker** [comment]
I'm also using an old version where fromJSON return optionals not eithers.

**Comment by ryanbooker** [comment]
Thanks. I'll look into that.

**Comment by CodaFi** [comment]
Absolutely!  If you find an elegant solution, please don't hesitate to shoot us a pull request if necessary.
